## Python Basics

#### Python is a general purpose programming language
#### Python is a high level language, easy to understand and user friendly
#### Python is dynamically typed
#### Python has a strong open source community
#### Python has abundant packages 
#### Python is fairly easy to interpret and learn.
#### Python handles different data structures very well.
#### Python has very powerful statistical and data visualization libraries.
#### In python indexing starts with 0

### Variables and datatypes

In [1]:
person_name = 'Andrew'
age = 48
is_DL_expert = True
height = 5.5
birth_year = 1970

In [2]:
print (type(height))
print (type(age))
print (type(person_name))
print (type(is_DL_expert))

<class 'float'>
<class 'int'>
<class 'str'>
<class 'bool'>


In [3]:
print (person_name)

Andrew


### Basic operations

In [4]:
a = 5
b = 2

In [5]:
print ('add:', a+b)
print ('subtract:', a-b)
print ('multiply:', a*b)
print ('divide:', a/b)
print ('a to the power b:', a**b)

add: 7
subtract: 3
multiply: 10
divide: 2.5
a to the power b: 25


In [6]:
a=3
b=4
print (a>b)
print (a<b)
print (a==b)


False
True
False


### Python Datastructure

### List

In [7]:
my_first_list = [3, 4, 1, 4, 5, 2, 7]
my_first_list

[3, 4, 1, 4, 5, 2, 7]

In [8]:
person = ['Andrew', 48, True, 5.5, 1970]
person

['Andrew', 48, True, 5.5, 1970]

In [9]:
# Access elements of list
print (person[0])
print (person[3])

Andrew
5.5


In [10]:
# to access last elemnt
person[-1]

1970

In [11]:
# to access range of elements
print (person[1:4])

[48, True, 5.5]


In [12]:
# to append
person.append('new_data')
person

['Andrew', 48, True, 5.5, 1970, 'new_data']

In [13]:
print (len(person))

6


In [14]:
# to delete
person.remove(1970)
print (person)
person.pop()
print (person)


['Andrew', 48, True, 5.5, 'new_data']
['Andrew', 48, True, 5.5]


In [15]:
person.append(['hobby',5000])
person

['Andrew', 48, True, 5.5, ['hobby', 5000]]

In [16]:
# accessing elemnt of a nested python list
person[-1][0]

'hobby'

### Dictionary

In [17]:
person_dict = {'name': 'Andrew', 'age': 48, 'is_DL_expert': True, 'height': 5.5, 'birth_year': 1990,
                          'attributes': ['hobby', 5000]}
person_dict

{'age': 48,
 'attributes': ['hobby', 5000],
 'birth_year': 1990,
 'height': 5.5,
 'is_DL_expert': True,
 'name': 'Andrew'}

In [18]:
print (person_dict['age'])
print (person_dict['attributes'])

48
['hobby', 5000]


### Tuple

In [19]:
book_list = ['A Game of Thrones', 'Digital Fortress', 'Practical Statistics for Data Scientists']
book_tuple = ('A Game of Thrones', 'Digital Fortress', 'Practical Statistics for Data Scientists')

In [20]:
book_list.append('sapiens')
book_list

['A Game of Thrones',
 'Digital Fortress',
 'Practical Statistics for Data Scientists',
 'sapiens']

In [21]:
book_tuple.append('sapiens')
book_tuple

AttributeError: 'tuple' object has no attribute 'append'

## Conditional statement

In [22]:
a = 10
b = 11
c = 10
if a == b:
    print('first condition is true')
elif a == c:
    print('second condition is true')
else:
    print('nothing is true. existence is pain.')

second condition is true


## For loop

In [23]:
for i in range(5):
    print (i)

0
1
2
3
4


In [24]:
book_list = ['A Game of Thrones', 'Digital Fortress', 'Practical Statistics for Data Scientists']
for elem in book_list:
    print (elem)

A Game of Thrones
Digital Fortress
Practical Statistics for Data Scientists


## importing libraries

In [25]:
import os
import numpy as np

### Numpy basics

In [26]:
np.__version__

'1.15.0'

In [27]:
#creating arrays
np.zeros(10, dtype='int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
#creating a 3 row x 5 column matrix
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
#create an array with a set sequence
np.arange(0, 20, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:

#create an array of even space between the given range of values
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:

#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

array([[ 1.4218705 ,  1.09475261, -0.37425294],
       [ 0.11137864, -1.30450975,  0.71346659],
       [ 0.60392338, -0.0432163 , -2.69002321]])

In [32]:
#create an identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#set a random seed
np.random.seed(0)


x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(3,4)) #two dimension
x3 = np.random.randint(10, size=(3,4,5)) #three dimension


print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


In [34]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
#array indexin is same as list indexing, it starts with 0

In [36]:
#assess value to index zero
print ('zero index:', x1[0])

#assess fifth value
print ('fifth value:', x1[4])

#get the last value
print ('last value:', x1[-1])


#get the second last value
print ('second last value:', x1[-2])


#in a multidimensional array, we need to specify row and column index

#1st row and 2nd column value
print ('value:', x2[2,3])

#3rd row and last value from the 3rd column
print('3 row, last value: ', x2[2,-1])

#replace value at 0,0 index
x2[0,0] = 12
print (x2)


zero index: 5
fifth value: 7
last value: 9
second last value: 7
value: 7
3 row, last value:  7
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
